title: "Catarina Pereira"
description: "PhD Candidate in Political Science
              #politicalcompetition
              #computationalsocialscience"
theme: jekyll-theme-minimal
baseurl: "" # the subpath of your site, e.g. /blog
google_scholar_url : "https://ct-p.github.io" # the base hostname & protocol for your site
email: "pereira@ipz.uzh.ch"

# Author details
author:
  name: "Catarina Pereira"
  email: "pereira@ipz.uzh.ch"

github:
  orcid_url: "https://orcid.org/0000-0002-0414-2511"
  google_scholar_url: "https://scholar.google.com/citations?user=F4vbvpMAAAAJ&hl=en&authuser=1"
